[package]
name = "search-suggest"
version.workspace = true
edition.workspace = true

[dependencies]
search-core = { workspace = true }
search-analysis = { workspace = true }
search-proto = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
