apiVersion: v1
kind: Service
metadata:
  name: suggest-headless
  namespace: search
  labels:
    app: suggest
spec:
  clusterIP: None
  selector:
    app: suggest
  ports:
    - name: grpc
      port: 9002
      targetPort: grpc
      protocol: TCP
